version: "2"
services:
  es:
    image: elasticsearch:5.6-alpine
    container_name: es
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/es.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/es:/usr/share/elasticsearch/data
      - ./logs/es:/usr/share/elasticsearch/logs
    networks:
      - net-es
  es1:
    image: elasticsearch:5.6-alpine
    container_name: es1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - ./elasticsearch/config/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/es1:/usr/share/elasticsearch/data
      - ./logs/es1:/usr/share/elasticsearch/logs
    networks:
      - net-es
  es2:
    image: elasticsearch:5.6-alpine
    container_name: es2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9202:9200"
      - "9302:9300"
    volumes:
      - ./elasticsearch/config/es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/es2:/usr/share/elasticsearch/data
      - ./logs/es2:/usr/share/elasticsearch/logs
    networks:
      - net-es
  elasticsearch-head:
    image: docker.io/mobz/elasticsearch-head:5
    container_name: es-head
    ports:
      - 9100:9100
    networks:
      - net-es
  kibana:
    container_name: kibana
    build:
      context: kibana/
    ports:
      - "5601:5601"
    networks:
      - net-es
    depends_on:
      - es

  # logstash:
  #   container_name: logstash
  #   build:
  #     context: logstash/
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - net-es
  #   depends_on:
  #     - es

networks:
  net-es:
